### ISSUE TITLE
Remove "assumed constructor" functionality (BREAKING CHANGE)

### ISSUE THREAD

**Issue by Benjamin-Dobell** [Benjamin-Dobell/IntelliJ-Luanalysis#12]
EmmyLua doesn't support callable types so it had a hack in place that meant if it detected a class being used as a function it'd _assume_ it was a constructor.

e.g. 

```lua
---@class SomeClass
local SomeClass = {}

---@type SomeClass
local someClass = SomeClass()
```

The assumption that calling a table returns an instance of that table's type may be incorrect, however even if it is correct, there's no known parameters to perform type checking against.

It's a breaking change, but I think the best course action is to outright remove the functionality. Users will instead be required to use Luanalysis' existing "Callable Types" functionality to define an overload on the class. Might be a bit of teething pain but I suspect users will find bugs they didn't know they had!

**Comment by Benjamin-Dobell** [comment]
Might be worth noting that I actually intended to remove support already:
https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/commit/912db7f3855039513ba5e348a0c92addb192d0eb

However, evidently there's still some related logic laying around.

**Comment by adriweb** [comment]
Would there be any way to get the behavior as default with an option for instance? For all tables variables as @class.
I just can't write @type for all instances all over my codebase, I have zillions...

At this point, letting the plugin know that classes return an instance of the same type, with a __call constructor bound to a method name (for instance "new", "init" (or whatever else users would set in the options), would be a great feature. Basically making the whole thing more seamless - a few options somewhere instead of a whole lot of extra annotations everywhere (who mixes several classes systems anyway...?)

**Comment by Benjamin-Dobell** [comment]
You don't (and won't) need to write `---@type` at all; I'm not sure I understand what you mean there.

Callable types will work exactly as they already do i.e. you define a function signature and it has a return value; it can be self e.g.

```lua
---@class SomeClass
---@overload fun(): self

local someClass = SomeClass()
```

Note that above `someClass` has the type `SomeClass` and there's no `---@type` involved.

**Comment by Benjamin-Dobell** [comment]
Actually, looks like I lied about the use of `self`. You have to be explicit about the return type i.e.

```lua
---@class SomeClass
---@overload fun(): SomeClass
local SomeClass = {}

local someClass = SomeClass()
```

However, the same logic applies i.e. there's no `---@type`.

**Comment by adriweb** [comment]
Alright I see, I got confused by the initial sample code. I'd love to have a way to make my class system annotated in such a way that the plugin knows what's going on and wouldn't need the @overload :p
