### ISSUE TITLE
Overrides are checked for static functions

### ISSUE THREAD

**Issue by Martmists-GH** [Benjamin-Dobell/IntelliJ-Luanalysis#138]
![Screenshot_20221020_155625](https://user-images.githubusercontent.com/16361449/196968839-51b1d758-24ec-4a94-947a-b14ab4ddbdb5.png)

**Comment by Benjamin-Dobell** [comment]
This is intended since your implementation of `button` is not a covariant of `widget`, the error reported is accurate. However, you can achieve what you're after with types like:

```
---@class widget
---@field common string

---@class button : widget
---@field text string
---@field callback fun(btn: button, x: number, y: number)

---@class static__widget
local widget = {}

function widget.create()
    return --[[---@type widget]] {
        common = "some common field"
    }
end

---@class static__button
---@field create fun(text: string, ): button
local button = {}

---@param text string
---@param callback (fun(btn: button, x: number, y: number))
function button.create(text, callback)
    local button = --[[---@type button]] widget.create()
    setmetatable(button, { __index = button })
    button.text = text
    button.callback = callback
    return button
end
```

Basically your static class can be given its own type, that does not incorrectly indicate it inherits from the static widget type. Your `button` however does still correctly inherit from `widget`.

This not just "correct", it's beneficial, you won't even see the `create` function on instances of `button`/`widget`, which is important, because they're not compatible.

![CleanShot 2023-01-16 at 14 48 50](https://user-images.githubusercontent.com/482276/212594867-a42a76dc-992f-4dcc-8cc5-197ea195a430.png)

![CleanShot 2023-01-16 at 14 49 01](https://user-images.githubusercontent.com/482276/212594857-a658d53a-d340-4df3-ac4c-3c6007c4f272.png)
