### ISSUE TITLE
Shape inspections incorrectly occuring on type cast shapes

### ISSUE THREAD

**Issue by dcorbin** [Benjamin-Dobell/IntelliJ-Luanalysis#14]
Environment
--------------
   name   |   version  
----------|----------
 IDEA version         | 2020.2
 Luanalysis version | 1.03
 OS                        | macOs 10.15.6

What are the steps to reproduce this issue?
------------------------------------------------
1. Run Inspect Code against his file:
```lua
---@alias VArgs std__Packed<any>

local result = --[[---@type std__Packed<any> ]] {n = 0}
local result = --[[---@type VArgs ]] {n = 0}
```

What happens?
-------------
The cast on the last line appears to have no effect, and and error is shown

What were you expecting to happen?
-----------------------------------------
The aliased type should behave the same as the original

**Comment by Benjamin-Dobell** [comment]
The description for this issue was a bit off as the type cast _was_ correctly occurring:

![Screen Shot 2020-08-07 at 1 47 04 am](https://user-images.githubusercontent.com/482276/89571407-f4001300-d86a-11ea-9af6-360fd96aa0ed.png)

It was a bit more complicated, and to-do with the functionality that provides inspections on table literals being assigned to a shape type. Although, the alias was involved in the example above, it'd occur in other circumstances too.
