### ISSUE TITLE
Is it possible to create a 'castable' generic class?

### ISSUE THREAD

**Issue by pouwelsjochem** [Benjamin-Dobell/IntelliJ-Luanalysis#62]
Environment
--------------
   name   |   version  
----------|----------
 IDEA version         | IC2020.3
 Luanalysis version | 1.2.2
 OS                        | MacOS Big Sur

What are the steps to reproduce this issue?
------------------------------------------------
```
---@generic T
---@return ShuffleBag<T>
local function newShuffleBag()
    local t = {} ---@class ShuffleBag<T>
    local allObjectsInOrder = {} ---@type T[]

    ---@param _amount number
    ---@param _object T
    function t:add(_amount, _object)
        for i = 1, _amount, 1 do
            allObjectsInOrder[#allObjectsInOrder + 1] = _object
        end
    end

    function t:roll()
        return table.remove(allObjectsInOrder, math.random(#allObjectsInOrder))
    end

    return t
end
```

What happens?
-------------
There seems to be no way to create such a structure. Because the `T` shadows the `@generic T`. Using a different name for T also doesn't work since `---@type T` can't detect that new name.

What were you expecting to happen?
-----------------------------------------
There to be a way to create a generic 'auto detectable' class. As in a class which extends its definition with the :add and :roll method here.

Any other comments?
------------------------
The way I think these objects could be generated would be the following:
```
local stringShuffleBag = --[[---@type ShuffleBag<string>]] newShuffleBag()
```

**Comment by Benjamin-Dobell** [comment]
## Explanation

Unfortunately, I don't believe there's any programming language / type system that will allow generics to be used this way. The reason this is forbidden is because you're attempting to use generic syntax to essentially declare (at runtime) a concrete (non-generic) class each time this function is invoked. That won't work in particular for Luanalysis because it's static typing only.

I'll try explain why, but it's a bit complicated!

Inside `newShuffleBag`'s body, `T` does not represent an unconstrained generic (i.e. any type). Instead it represents a _specific_ type.

For example, the following is illegal:

```lua
---@generic A : string
---@generic B : string
---@param a A
---@param b B
---@return A
local function foo(a, b)
    a = b
    return a
end
```

Inside the function body, `A` and `B` are a _specific_ type, but we don't know _what_ type they. Even though in this case we've constrained them to both being strings, we still don't know what type of string they are. There's no variance guarantees made between these types. If the above were allowed then so would this be allowed:

```lua
---@type "a"
local a = "a"

a = foo(a, "b") -- If the above function definition were legal, this would allow assigning "b" to `a`.
```

So the issue isn't really the shadowing. If you were to use a different type name, it doesn't make any sense to declare/define a class inside a function using a generic parameter belonging to another scope. That's because in your class is using a specific (albeit unknown) `T`.

## Correct (Verbose) Solution

The only _correct_, albeit annoyingly verbose solution, is to explicitly declare generic classes, with explicit fields. There's an example at https://github.com/Benjamin-Dobell/ge_tts/blob/master/InfiniteContainerInstance.ttslua

This has it's own problems whereby you can't define overloads, unless you get callable shapes involved.

## Hacky Work-around

I've just noticed you can actually trick the type system with:

```lua
---@generic S
local function newShuffleBag()
    local t = {} ---@class ShuffleBag<T: S>
    local allObjectsInOrder = {} ---@type S[]
```

It doesn't really make any sense though, especially since there's no way to give `S` a concrete type, because function generic parameter are _always_ inferred (can't be specified explicitly).

Even if you added a parameter so `S` could be inferred, it still doesn't make any sense due to what I described above i.e. `S` is a specific _albeit unknown_ type. There's no way you can ever provide a T that meets that unknown constraint. _But_, for whatever reason (bugs) it does seem to work at the moment 🤷‍♂️

**Comment by Benjamin-Dobell** [comment]
Unfortunately, I don't think this one is actionable without breaking type system constraints. I've no doubt that explicit typing needs to be improved though, feel free to open any related issues you run into.
