### ISSUE TITLE
@field function with optional parameters

### ISSUE THREAD

**Issue by kerwanp** [Benjamin-Dobell/IntelliJ-Luanalysis#76]
Environment
--------------
   name   |   version  
----------|----------
 IDEA version         |  2021.1.2 Build #IU-211.7442.40
 Luanalysis version |  v1.2.3
 OS                        | Windows 10

What are the steps to reproduce this issue?
------------------------------------------------
I am trying to create a `typing` file for a public Lua API.
For that I basically use `@class` and `@field`, and I've been able to generate a clean version but I still have a problem with function that contains optional parameters.

1. Create a new Lua file with the following content
```
--- @class Test
--- @field Test fun(a: number, b)
Test = {}

Test.Test(5)
```

What happens?
-------------
I get the error `Missing argument: b: null  `

What were you expecting to happen?
-----------------------------------------
Being able to define if an argument is optional or not in LDoc (eg: `--- @field Test fun(a: number, b = nil): EventListener`)

Any logs, error output, etc?
------------------------------
`Missing argument: b: null  `

Any other comments?
------------------------
I tried differents configurations:
```
--- @field Test fun(a: number, b: void)
--- @field Test fun(a: number, b: nil)
--- @field Test fun(a: number, b: any)
--- @field Test fun(a: number, b = nil)
--- @field Test fun(a: number, b?)
```

**Comment by adriweb** [comment]
See https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/issues/39

**Comment by Benjamin-Dobell** [comment]
You'll want to follow the lead of the stdlib definitions. Basically, you declare a class as you've done, however you then declare functions using regular Lua syntax i.e. the same syntax you'd use to implement them. You can then specify `@overload`. The fact that the definitions happen to use the same syntax as real Lua code ends up being irrelevant because you won't actually include (i.e. `require`) your definitions in your program.

Please see https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/tree/master/src/main/resources/std/Lua53 for an example.

There is one noticeable trick though. It's highly recommended that you use the `.def.lua` file extension, this will automatically suppress errors that are irrelevant for definition files e.g. complaints about not return statements - as you won't actually be implementing the functions in the definition files.

**Comment by Benjamin-Dobell** [comment]
@kerwanp By the way, if you have further questions, as opposed to bugs/issues, then feel free to jump into this Discord https://discord.gg/xrqynr2 then the `#luanalysis-ide` channel.

The Discord is _technically_ meant to be for Tabletop Simulator modding community. However, I frequent the aforementioned channel and off-topic Lua chatter is welcome in the `#off-topic` channel - you could just mute all the other channels if you've no interest in Tabletop Simulator.
