### ISSUE TITLE
Improve string.match documentation

### ISSUE THREAD

**Issue by rillig** [Benjamin-Dobell/IntelliJ-Luanalysis#80]
The return type for `string.match` [is annotated as](https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/blob/0b53e920af6f1e56a9e39f2ba57a77dde93055f7/src/main/resources/std/Lua53/string.def.lua#L224) `nil | (number | string, (number | string)...)`. The textual documentation around that type annotation does not mention any numerical returns though.

I had a quick glance at the implementation in `lstrlib.c`, function `str_match`, and from that it seemed that only `string.find` can return numbers, but not `string.match`.

Either the documentation should mention the cases in which a number can be returned, or the type annotation should be corrected, probably to `nil | (string, string...)`.

**Comment by Benjamin-Dobell** [comment]
The documentation is largely the official Lua docs i.e. https://www.lua.org/manual/5.3/manual.html#pdf-string.match. Although, admittedly, it does have a link to https://www.lua.org/manual/5.3/manual.html#6.4.1 where captures are explained. Specifically, numbers are returned as per:

> As a special case, the empty capture () captures the current string position (a number). For instance, if we apply the pattern "()aa()" on the string "flaaap", there will be two captures: 3 and 5. 

If you use Git (or Github) blame you can see the change was made in https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/commit/5a3ffa4de83fa801448cd85fee2abcab9086db24

As for updating the documentation, I think that's a reasonable request. Especially since this isn't the first time this particular question has come up. I don't think we can realistically include the entire capture documentation inline, however something for this case in particular is warranted

**Comment by rillig** [comment]
Thank you very much for this explanation. I looked up the Lua source code again, and `get_onecapture` indeed pushes an integer on the Lua stack. I hadn't seen this yesterday since I was too biased from Java programming, where `get` functions don't have side-effects, so I didn't delve into that function. :)

**Comment by Benjamin-Dobell** [comment]
> Is it currently possible to restrict the return type of `string.match` to `nil | (string, string...)` in case the pattern is a string literal that doesn't contain the positional capture group `()`?

Sorry. Just noticed this question. Unfortunately, no that's not possible. The best you can do is cast.

Unfortunately, this is one piece of functionality that I've no plans of implementing. Whilst it'd be pretty nifty being able to run a regex on a string and factor that into the type inference, it adds a lot of complexity both in implementation and in writing the types themselves.
