### ISSUE TITLE
Modifying table breaking assignment.

### ISSUE THREAD

**Issue by HaniiPuppy** [Benjamin-Dobell/IntelliJ-Luanalysis#83]
Environment
--------------
   name   |   version  
----------|----------
 IDEA version         | 2021.1.2 build #IC-211.7442.40
 Luanalysis version | 1.2.3
 OS                        | Mac OS X 10.13.6
------------------------------------------------
Code that causes this issue: https://pastebin.com/Mzcmadrz
------------------------------------------------
The issue:

When I edit the "gameHandler" table, (at line 365) even just by removing a trailing comma and re-adding it, "gameHandler" gets underlined with the message "Undeclared variable 'gameHandler'."

When this is the case, trying to access members of "gameHandler" outwith it act as though it doesn't exist or have the members it has.

This happens about half the time any edit is made, but not all the time. Often enough to be annoying. Deleting the "=" after "gameHandler", waiting a second, and re-adding it fixes the issue until the next time it pops up.

When this happens, IntelliJ Idea spits up one or both of the following IDE errors:

https://pastebin.com/mhmwgWqa

https://pastebin.com/BiMfpvtv

**Comment by HaniiPuppy** [comment]
It seems to be something in the `gameHandler.getPlayerRecord` function in the example code I provided. Removing that function causes this to no longer happen.

**Comment by Benjamin-Dobell** [comment]
The pastebin links are now dead, so unfortunately I can't check this out anymore. However, there's been a _lot_ of fixes since 1.2.3, so I'm going to assume this is fixed in 1.4.0. If it's not. Feel free to re-open and share a gist etc.

P.S. Waiting on Jetbrains to review 1.4.0, however you can download and install the .zip from [Github](https://github.com/Benjamin-Dobell/IntelliJ-Luanalysis/releases)].
